name: surco
description: Frontend del proyecto DEL SURCO A TU MESA

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-146.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.3.6
  flutter_speed_dial: ^7.0.0
  flutter_staggered_grid_view: ^0.6.2
  formz: ^0.6.0
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  http: ^1.1.0
  image_picker: ^0.8.7+5
  animate_do: ^3.0.2
  provider: ^6.0.5
  url_launcher: ^6.1.11
  video_player: ^2.6.1
  shared_preferences: ^2.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/Surco_logotipo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - assets/icon/
    - assets/videos/